coverage:
  precision: 2
  round: down
  range: "80...100"

comment:
  layout: "header, diff, components"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 5%
  # let's ignore the typo about modbstcp、zLan and keep the original component_id
  individual_components:
    - component_id: stdunit_tags_core 
      name: "Core" 
      paths:
        - "src/StdUnit.Tags.Core/**"
    - component_id: stdunit_tags
      name: "Tags"
      paths:
        - "src/StdUnit.Tags/**"
    - component_id: stdunit_tags_s7
      name: "S7"
      paths:
        - "src/StdUnit.Tags.S7/**"
    - component_id: stdunit_tags_modbstcp
      name: "ModbusTcp"
      paths:
        - "src/StdUnit.Tags.ModbusTcp/**"
    - component_id: stdunit_tags_opcuaclient
      name: "OpcUaClient"
      paths:
        - "src/StdUnit.Tags.OpcUaClient/**"
    - component_id: stdunit_tags_hjzk
      name: "Hjzk"
      paths:
        - "src/StdUnit.Tags.Hjzk/**"
    - component_id: stdunit_tags_zLan
      name: "ZLan"
      paths:
        - "src/StdUnit.Tags.ZLan/**"
    - component_id: stdunit_tags_comscanner
      name: "Com"
      paths:
        - "src/StdUnit.Tags.ComScanner/**"
    - component_id: stdunit_tags_rx
      name: "Rx"
      paths:
        - "src/StdUnit.Tags.RxExtensions/**"
    - component_id: stdunit_tags_r3
      name: "R3"
      paths:
        - "src/StdUnit.Tags.R3Extensions/**"
    - component_id: stdunit_tags_mcpserver
      name: "McpServer"
      paths:
        - "src/StdUnit.Tags.McpServer/**"
    - component_id: stdunit_tags_simplefiles
      name: "SimpleFiles"
      paths:
        - "src/StdUnit.Tags.SimpleFiles/**"

ignore:
  - "**/*.md"
  - "**/*.yml"
  - "src/StdUnit.Tags.Tests/**"
  - "**/*.g.cs"