<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>依赖于 StdUnit.Tags.Core，补充项目、日志、插件等功能</Description>
    <TargetFrameworks>net8.0;net472</TargetFrameworks>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <XmlSerializerGeneration>GenerateSerializationAssembly</XmlSerializerGeneration>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StdUnit.Tags.Core\StdUnit.Tags.Core.csproj" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>