<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<Description>Blazor 组件库（核心）：测点树与通道的查看、编辑组件</Description>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>StdUnit.Tags.BlazorLib</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\StdUnit.Tags.R3Extensions\StdUnit.Tags.R3Extensions.csproj" />
		<ProjectReference Include="..\StdUnit.Tags\StdUnit.Tags.csproj" />
	</ItemGroup>
	<Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
